### PR TITLE
Fix the issue with debounce

### PR DESCRIPTION
**Pull request by pangwa**
The latest callback will not be called with the debounce function.

It will not work at below case:
1. var cb = debounce(func, 10, true);
2. cb(opt1); -> setTimeout 10 -> func
3. When the timeout callback was called, it checkes the
   whether the immediate flag was set,
  and it won't call the callback actually

### CODE REVIEW

**Comment by krispo** [comment]
In your code `callNow` will always be `true`, if `immediate==true`.

**Comment by pangwa** [comment]
What's the purpose of the immediate flag? I'm not quite clear on the use of this flag. Is the callback supposed to be called without timeout if the immediate flag was set?

**Comment by pangwa** [comment]
Or should change the callNow statement to below?
                        var callNow = immediate && timeout;

which will always delay the call callback function call first time and apply it immediately on the second call.

**Comment by krispo** [comment]
if immediate=true, callback is applied immediately if there were no any calls before in specified time interval. if immediate=false, callback is applied (function `later`) after specified time interval and if there were no any calls in this interval.

**Comment by pangwa** [comment]
Ok, I see, please see the updated PR.

The bug it fixed is below:
1. var cb = debounce(func, 10, true);
2. cb(opt1) -> setTimeout(later);
3. cb(opt2) before the timeout happens -> clearTimeout() ->setTimeout(later)
4. when the later function was called with the second timeout, func will not be called as the immediate flag was true.

**Comment by krispo** [comment]
When the later function was called with the second timeout, func should not be applied. We don't want to apply the func twice if immediate==true.
In your case if we call the func twice immediately, the func will be applied twice (the first call, and the second call after second timeout, since `callNow==false` already), but we want to apply only once.

**Comment by pangwa** [comment]
Yes, that's what I want to fix actually.  This will prevent the latest change(config/data) applied to the graph in some cases.  I met an issue with this design while updating the chart height, data with the data returned from the server. I found sometimes the graph's height stays the original size randomly which caused the interval between initializing and updating the debounce function are too short, thus the chart  were not updated...

**Comment by krispo** [comment]
You can change debounce interval in config. Also you can try to update or refresh the chart via api when needed.

**Comment by pangwa** [comment]
changing debounce interval just reduce the possibility of this issue. Updating/refresing the chart via api requires extra work.... Could we provide an option to disable the debounce behavior? Since it could causes issues.

**Comment by krispo** [comment]
What about `debounce: 0` in config? Also update to the latest version.

**Comment by pangwa** [comment]
thanks, it sounds great. I'll close this issue.

**Pull request closed without merging**
