### PR TITLE
Fixed issue with stacked bar charts

### PR DESCRIPTION
**Pull request by inolasco**

### CODE REVIEW

**Comment by NameFILIP** [comment]
Hi Ivan, could you describe what was the issue that is fixed by this PR?

**Comment by inolasco** [comment]
@NameFILIP Sure. The issue is best described in https://github.com/krispo/angular-nvd3/issues/100#issuecomment-90751376, which is the issue I created for it. I should have created the pull request linked to the issue or viceversa, just didn't know how to at the time :P

**Comment by inolasco** [comment]
Also, it seems other people have created separate issues for the same bug. probably fixing one will close the all. See https://github.com/krispo/angular-nvd3/search?q=stacked&type=Issues

**Comment by NameFILIP** [comment]
Modified a little bit and merged https://github.com/krispo/angular-nvd3/commit/d3881603572fadf5ee091ee1f83c3ff3693375c5
Not the most beautiful solution, but it works.

**Comment by jerrybk108** [comment]
Thanks for your great support!
Best regards,
Hieu Tran

**Pull request merged**
