### PR TITLE
Subtitle: replace non working jqLite find() method for class name

### PR DESCRIPTION
**Pull request by ValentinGot**
Subtitle isn't displayed because jqLite find() method does not support selectors.

From angular documentation :
```find() - Limited to lookups by tag name```

### CODE REVIEW

**Comment by krispo** [comment]
Exactly, thanks!

**Comment by ValentinGot** [comment]
No problem :)

Could you release it plz ?

**Comment by krispo** [comment]
Sure, release will be in the coming days. Need to test some resize issues.

**Comment by ValentinGot** [comment]
Yep sure, thanks.

**Pull request merged**
