### PR TITLE
Arguments available for subscribed events.

### PR DESCRIPTION
**Pull request by ghs**

### CODE REVIEW

**Comment by krispo** [comment]
Thanks!

**Comment by oumayma-ltaief** [comment]
Hello krispo, 
I'm using your plugin, especially the discreteBarChart type. I need to not show the labels just like the option for hiding the values that your plugin gives which is : showValues: true
Can you please tell me which option can help me for that?
Thank you.

**Comment by krispo** [comment]
What labels?
```js
chart: {
    showXAxis: false, // hide x-axis labels
    showYAxis: false, // hide y-axis labels
    tooltips: false // hide tooltips
}
```

**Comment by oumayma-ltaief** [comment]
Thanks Krisp, I was talking about the XAxis label so this helped me : showYAxis: false

**Comment by oumayma-ltaief** [comment]
Krispo, in fact I have an other question; 
in the type discreteBarChart, a click on a baton of the histogram I get a value with one only number after the "," of the decimal whole number.
I need to display the value just in the format(',.2f') even on the clic.
Can you tell me how to fix that please?
Thanks.

**Comment by krispo** [comment]
What button of the histogram do you click?

**Comment by oumayma-ltaief** [comment]
I mean the clic on the tooltips

**Comment by krispo** [comment]
```js
chart: {
    yAxis: {
        tickFormat: function (d){ return d3.format(',.2f')(d); } // label format for y-axis
    },
    tooltip: {
        valueFormatter: function (d){ return d3.format(',.2f')(d); } // value format for tooltip
    }
}
```

**Comment by oumayma-ltaief** [comment]
Thank you.

**Comment by oumayma-ltaief** [comment]
Hello Krisop,
is there the option of displaying legend for the histogram with the type 'discreteBarChart' like in 'pieChart' type? Thanks.

**Comment by krispo** [comment]
there is no legend for `discreteBarChart`

**Comment by oumayma-ltaief** [comment]
I'm using your plugin with my ionic app, in fact why I asked for the legend: because while testing the clic on the tooltip to see the (color, description, value) with my android lolipop device the clic doesn't give this but any other older version of android device give it correctly.

**Comment by oumayma-ltaief** [comment]
Could I configure the width of the representations of the discreteBarChart type please not just the width of the whole chart?

**Pull request merged**
