### PR TITLE
Added zoom option

### PR DESCRIPTION
**Pull request by tejaspathak**
#### Thanks community members for the great work. This is only peer review and getting feedback from community. 

I needed zoom feature #216 for scatterCharts, hence this change. I am relatively new to javascript app development and sources related to this project, so kindly let me know your feedback on how this feature could be integrated.

- nvd3 does not expose zoom feature of d3, this change add this feature so that angular apps can make use of d3 zoom.
- Currently only tested with scatterChart. Needs to be tested/configured appropriately for other charts.
- This approach needs to be checked with community developers.
- Updated dependent libraries.

### CODE REVIEW

**Comment by krispo** [comment]
Great work, thanks! It looks promising.
Can you please re-pull your zoom feature without changing files in the `lib/` folder (it's not relevant and  removed currently), that contained the fixed assembly for an old nvd3 version.

**Comment by tejaspathak** [comment]
Done. Following is example
```
$scope.options = {
                 /* Chart options ... */

                zoom: {
                    //NOTE: All attributes below are optional
                    scale: 1,
                    scaleExtent: [1,10],
                    translation: [0,0],
                    zoomed: function(xDomain, yDomain) {
                        var domains = {x1: 0, x2: 0, y1: 1, y2: 1};
                        return domains;
                    },
                    unzoomed: function(xDomain, yDomain) {
                        var domains = {x1: 0, x2: 0, y1: 0, y2: 0};
                        return domains;
                    },
                    unzoomEventType: 'dblclick.zoom'
                }
}
```

**Comment by krispo** [comment]
It looks just awesome!!! 
I've stylized the code a bit and added some options. It works also with some other charts. This is a really cool stuff, thanks mate!

**Comment by tejaspathak** [comment]
I am glad you found it useful, thanks :)

**Pull request merged**
